name: EditorLint

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: editor-lint
        run: make lint
