name: EditorLint

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: Linter-check
        run:
          pip install poetry
          make lint